apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  # different name
  name: letsencrypt-prod
  namespace: default
spec:
  acme:
    # now pointing to Let's Encrypt production API
    server: https://acme-v02.api.letsencrypt.org/directory
    email: tsadimas@gmail.com
    privateKeySecretRef:
      # storing key material for the ACME account in dedicated secret
      name: account-key-prod
    solvers:
    - http01:
       ingress:
         class: public