apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-traefik
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  ingressClassName: traefik
  rules:
  - host: "spring.tsadimas.dns-cloud.net"
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: spring
            port:
              name: spring